name: PHPMD

on: push

jobs:
  phpmd:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    env:
      MEMCACHED_HOST: localhost
      MEMCACHED_PORT: 11211
      COOKIE_NAME: '_test'

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1
          args: --ignore-platform-req=ext-memcached

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: src,tests
          output: text
          ruleset: cleancode,codesize,controversial,design,naming,unusedcode
