name: PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    env:
      MEMCACHED_HOST: localhost
      MEMCACHED_PORT: 11211
      COOKIE_NAME: '_test'

    steps:
      - name: install libraries
        run: sudo apt install -y zip git libzip-dev libcurl3-dev libssl-dev libmemcached-dev
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, zip, pcntl, xml, curl, json, xdebug, memcached

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-memcached

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml
